"""Initial migration

Revision ID: e87d0ba6ae6d
Revises: 
Create Date: 2025-09-15 00:47:07.934575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87d0ba6ae6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_days', sa.Float(), nullable=False))
        batch_op.drop_column('total_days')
        batch_op.drop_column('used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('total_days', sa.INTEGER(), nullable=True))
        batch_op.drop_column('used_days')

    # ### end Alembic commands ###
